### ISSUE TITLE
Does the python library support implication ( --> )?

### ISSUE THREAD

**Issue by arjunarunasalam** [anand-bala/signal-temporal-logic#3]
I am unable to figure out how to write a statement with implication in python
eg: a --> b

Is there a python binding for implication? An example of how to write that statement in python would be helpful!

Thanks!

**Comment by anand-bala** [comment]
There is currently no way to write logical implications in Python using the syntax `a -> b` (this is a Python problem). The easiest way to do this would be `~a | b`.

I'll try adding an `stl.Implies(a, b)` function in the new API I'm writing.

**Comment by arjunarunasalam** [comment]
Thank you for the quick response. What about the next operator in python?  Is there a workaround for this? Thank you in advance.

**Comment by anand-bala** [comment]
So the current version of the library doesn't actually support `Next` since it is supposed to be Signal Temporal Logic (and `Nex` doesn't make sense for continuous-time signals). But the new version I am working on supports both MTL and STL, with a few different monitors for both.

**Comment by arjunarunasalam** [comment]
Thank you for the responses. Appreciate it :)  Looking forward to the new version.
